AutoAttendance/AutoAttendance/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AutoAttendance.Models
{
    public class Student
    {
        [Key]
        [Column(Order = 10)]
        public string ApplicationUserId { get; set; }
        [Key]
        [Display(Name="Class")]
        [Column(Order = 20)]
        public string ClassName { get; set; }
        [Key]
        [Column(Order = 30)]
        public string Id { get; set; }

        public string Name { get; set; }
        public string present { get; set; }
    }
}

AutoAttendance/AutoAttendance/Controllers/ClassNameController.cs
using AutoAttendance.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace AutoAttendance.Controllers
{
    public class ClassNameController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        // GET: ClassName
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View(db.ClassNames.Where(className => className.ApplicationUserId == User.Identity.Name));
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        
        // GET: ClassName
        public ActionResult IndexAttendance()
        {
            if (User.Identity.IsAuthenticated)
            {

                return View(db.ClassNames.Where(className => className.ApplicationUserId == User.Identity.Name));
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult Index(string SelectClass)
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Student", new { className = SelectClass });
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult IndexAttendance(string SelectClass)
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Attendance", "Student", new { className = SelectClass });
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: ClassName/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ClassName/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClassName/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ClassName/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ClassName/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ClassName/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ClassName/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AutoAttendance/AutoAttendance/Controllers/StudentController.cs
using AutoAttendance.Models;
using ClosedXML.Excel;
using FastMember;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace AutoAttendance.Controllers
{
    public class StudentController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        // GET: Student
        public ActionResult Index(string className, string sortOrder)
        {
            if (User.Identity.IsAuthenticated)
            {
                IEnumerable<Student> students = null;
                if(className == null)
                {
                    className = ViewBag.className;
                }
                else
                {
                    ViewBag.className = className;
                }
                if (className == null)
                {
                    ViewBag.Message = "Since no class is selected, displaying all class students!!";
                    //ViewBag.className = className;
                    students = db.Students.Where(student => (student.ApplicationUserId == User.Identity.Name));
                }
                else
                {
                    students = db.Students.Where(student => (student.ApplicationUserId == User.Identity.Name && student.ClassName == className));
                }

                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                ViewBag.idSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";

                switch (sortOrder)
                {
                    case "name_desc":
                        students = students.OrderByDescending(s => s.Name);
                        break;
                    case "id_desc":
                        students = students.OrderBy(s => s.Id);
                        break;
                    default:
                        students = students.OrderBy(s => s.Name);
                        break;
                }

                return View(students.ToList());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Student/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Student/Create
        public ActionResult Create(string ClassName)
        {
            if (User.Identity.IsAuthenticated)
            {
                if(ClassName != null)
                {
                    ViewBag.className = ClassName;
                }

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: Student/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "ClassName,Id,Name,ApplicationUserId")] Student student)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    student.ApplicationUserId = User.Identity.Name;

                    object[] queryParamsStudent = new object[3];
                    queryParamsStudent[0] = User.Identity.Name;
                    queryParamsStudent[1] = student.ClassName;
                    queryParamsStudent[2] = student.Id;
                    Student studentExisting = db.Students.Find(queryParamsStudent);

                    if (studentExisting != null)
                    {
                        ViewBag.Message = "This Student already exist in same class!!";
                        return View(student);
                    }
                    else
                    {
                        db.Students.Add(student);
                        db.SaveChanges();
                    }

                    object[] queryParams = new object[2];
                    queryParams[0] = User.Identity.Name;
                    queryParams[1] = student.ClassName;
                    
                    ClassName className = db.ClassNames.Find(queryParams);
                    if(className == null)
                    {
                        ClassName newClass = new ClassName();
                        newClass.ApplicationUserId = User.Identity.Name;
                        newClass.CName = student.ClassName;

                        db.ClassNames.Add(newClass);
                        db.SaveChanges();
                    }

                    return RedirectToAction("Index", new { className = student.ClassName });
                    
                }
                return View(student);
            }
            catch
            {
                return View(student);
            }
        }

        // GET: Student/Edit/5
        public ActionResult Edit(string id, string className)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            object[] queryParams = new object[3];
            queryParams[0] = User.Identity.Name;
            queryParams[1] = className;
            queryParams[2] = id;
            Student student = db.Students.Find(queryParams);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Student/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "ClassName,Id,Name")] Student student)
        {
            if (ModelState.IsValid)
            {
                student.ApplicationUserId = User.Identity.Name;
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { className = student.ClassName });
            }
            return View(student);
        }

        // GET: Student/Delete/5
        public ActionResult Delete(string id, string className)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            object[] queryParams = new object[3];
            queryParams[0] = User.Identity.Name;
            queryParams[1] = className;
            queryParams[2] = id;

            Student student = db.Students.Find(queryParams);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Student/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id, string className)
        {
            object[] queryParams = new object[3];
            queryParams[0] = User.Identity.Name;
            queryParams[1] = className;
            queryParams[2] = id;

            Student student = db.Students.Find(queryParams);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index", new { className = student.ClassName });
        }

        // GET: Student
        public ActionResult Attendance(string className, string sortOrder)
        {
            if (User.Identity.IsAuthenticated)
            {
                
                IEnumerable<Student> students = null;
                if (className == null)
                {
                    className = ViewBag.className;
                }
                else
                {
                    ViewBag.className = className;
                }
                if (className == null)
                {
                    ViewBag.Message = "Since no class is selected, displaying all class students!!";
                    students = db.Students.Where(student => (student.ApplicationUserId == User.Identity.Name)).ToList();
                }
                else
                {
                    students = db.Students.Where(student => (student.ApplicationUserId == User.Identity.Name && student.ClassName == className)).ToList();
                }

                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                ViewBag.idSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";

                switch (sortOrder)
                {
                    case "name_desc":
                        students = students.OrderByDescending(s => s.Name);
                        break;
                    case "id_desc":
                        students = students.OrderBy(s => s.Id);
                        break;
                    default:
                        students = students.OrderBy(s => s.Name);
                        break;
                }
                
                return View(students.ToList());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult Attendance(Student students, string[] Present, string submitButton, string[] late)
        {

            GridView gridview = new GridView();

            //List<Student> studentList = db.Students.Where(student => student.ApplicationUserId == User.Identity.Name && student.ClassName == students.ClassName).ToList();

            var studentList = (from d in db.Students
                               where d.ApplicationUserId == User.Identity.Name && d.ClassName == students.ClassName
                               select new
                               {
                                   Id = d.Id,
                                   Name = d.Name,
                                   Present = d.present
                               }).ToList();

            List<StudentExcel> studentExcel = new List<StudentExcel>();

            foreach (var student in studentList)
            {

AutoAttendance/AutoAttendance/Views/Student/Attendance.cshtml
@model IEnumerable<AutoAttendance.Models.Student>

@{
    ViewBag.Title = "Attendance Sheet";
    <div class="text-danger">
        <h3>@ViewBag.Message</h3>
    </div>
    <div class="text-success">
        <h3>@ViewBag.ActionMessage</h3>
    </div>
}

<!-- Search Form -->
<form id="labnol" method="post">
    <h2>Attendance Sheet
    <input type="hidden" name="speech" id="transcript" placeholder="Speak" />
    <img onclick="startDictation()" src="//i.imgur.com/cHidSVu.gif" />

    </h2>
</form>

@using (Html.BeginForm())
{
    
    <div class="form-group" method="post">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ClassName)
                </th>
                <th>
                    @Html.ActionLink("Id", "Attendance", new { sortOrder = ViewBag.idSortParm, className = ViewBag.className })
                </th>
                <th>
                    @Html.ActionLink("Name", "Attendance", new { sortOrder = ViewBag.NameSortParm, className = ViewBag.className })
                </th>
                <th>
                    Present
                </th>
                <th>
                    Late
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ClassName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <input type="checkbox" name="Present" value="@(item.Id)" id="@(item.Id)" onchange="changeLate(@(item.Id))">
                    </td>
                    <td>
                        <input type="checkbox" name="Late" value="late_@(item.Id)" id="late_@(item.Id)" onchange="changePresent(@(item.Id))">
                    </td>
                </tr>

                string studID = item.Id;
                string studName = item.Name;

                //var myList = new Array();
                //myList.push('Hello');

            }
        </table>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col-md-10">
                @Html.ActionLink("View Another Class", "IndexAttendance", "ClassName", null, new { @class = "btn btn-default" })
                <input type="submit" value="Download" name="submitButton" class="btn btn-default" />
                <input type="submit" value="Email" name="submitButton" class="btn btn-default" />
            </div>

        </div>
    </div>

}

<!-- CSS Styles -->
<style>
    .speech {
        border: 1px solid #DDD;
        width: 300px;
        padding: 0;
        margin: 0;
    }

        .speech input {
            border: 0;
            width: 240px;
            display: inline-block;
            height: 30px;
        }

        .speech img {
            float: right;
            width: 40px;
        }
</style>

<!-- HTML5 Speech Recognition API -->
<script>

    var currentId = "";

    function startDictation() {

        if (window.hasOwnProperty('webkitSpeechRecognition')) {

            var studList = [];
            var map = new Object();

            var names = "";

            @foreach (AutoAttendance.Models.Student stud in Model)
            {
                var nameLower = stud.Name;
                nameLower = nameLower.ToLower();
                <text>
                    map["@nameLower"] = "@stud.Id";
                </text>
            }

            var recognition = new webkitSpeechRecognition();
            recognition.continuous = true;
            recognition.interimResults = false;

            recognition.lang = "en-US";
            recognition.start();
            recognition.onresult = function (e) {
                var currentStud = "";

                for (var i = e.resultIndex; i < e.results.length; ++i) {
                    if (e.results[i].isFinal) {
                        var word = e.results[i][0].transcript;
                        word = word.trim().toLowerCase();
                        if (word == "yes" || word == "yes sir" || word == "yes ma'am" || word == "present") {
                            document.getElementById(currentId).checked = true;
                        } else {
                            currentId = map[word];
                        }
                    }
                }
            }
        }
    }


    function speak(text, callback) {
        var u = new SpeechSynthesisUtterance();
        u.text = text;
        u.lang = 'en-US';

        u.onend = function () {
            if (callback) {
                callback();
            }
        };

        u.onerror = function (e) {
            if (callback) {
                callback(e);
            }
        };

        speechSynthesis.speak(u);
    }

    function sleep(milliseconds) {
        var start = new Date().getTime();
        for (var i = 0; i < 1e7; i++) {
            if ((new Date().getTime() - start) > milliseconds) {
                break;
            }
        }
    }

    function changePresent(id) {
        var lateId = "late_" + id;
        if (document.getElementById(lateId).checked) {
            document.getElementById(id).checked = true;
        }
    }

    function changeLate(id) {
        var lateId = "late_" + id;
        if (!document.getElementById(id).checked) {
            document.getElementById(lateId).checked = false;
        }
    }

</script>
  

AutoAttendance/AutoAttendance/Views/Student/Create.cshtml
@model AutoAttendance.Models.Student

@{
    ViewBag.Title = "Create Student";
    <div class="text-danger">
        <h3>@ViewBag.Message</h3>
    </div>
}

<h2>Create Student</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClassName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.ClassName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                @*@Html.ActionLink("View Student List", "Index", "Student", new { className = ViewBag.className }, new { @class = "btn btn-default" })*@
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AutoAttendance/AutoAttendance/Views/Student/Delete.cshtml
@model AutoAttendance.Models.Student

@{
    ViewBag.Title = "Delete Student";
}

<h2>Delete Student</h2>

<h3>Are you sure you want to delete this student?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
            @Html.ActionLink("Back to Student List", "Index", new { className = Model.ClassName }, new { @class = "btn btn-default" })
        </div>
    }
</div>

AutoAttendance/AutoAttendance/Views/Student/Edit.cshtml
@model AutoAttendance.Models.Student

@{
    ViewBag.Title = "Edit Student";
}

<h2>Edit Student</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ClassName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly"} })
                @Html.ValidationMessageFor(model => model.ClassName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                @Html.ActionLink("Back to Student List", "Index", new { className = Model.ClassName }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AutoAttendance/AutoAttendance/Views/Student/Index.cshtml
@model IEnumerable<AutoAttendance.Models.Student>

@{
    ViewBag.Title = "Student List";

    <div class="text-danger">
        <h3>@ViewBag.Message</h3>
    </div>
}

<h2>Student List</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ClassName)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Id)*@
            @Html.ActionLink("Id", "Index", new { sortOrder = ViewBag.idSortParm, className = ViewBag.className })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Name)*@
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, className = ViewBag.className })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ClassName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id, className = item.ClassName }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id, className = item.ClassName })
                @{ViewBag.classNameVal = item.ClassName;}
            </td>
        </tr>
    }

</table>

<div class="row">
    <div class="col-md-4">
        <p>
            @Html.ActionLink("Create New Student", "Create", "Student", new { className = ViewBag.classNameVal }, new { @class = "btn btn-default" })
            @Html.ActionLink("View Another Class", "Index", "ClassName", null, new { @class = "btn btn-default" })
        </p>
    </div>
</div>